version: "3.8"
services:
    app:
        container_name: lion-framework-app
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
        networks:
            - lion
    db:
        image: mysql
        container_name: lion-framework-mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - lion
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: lion-framework-phpmyadmin
        links:
            - db:db
        ports:
            - 8080:80
        environment:
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        networks:
            - lion
volumes:
    db_data:
networks:
    lion:
